### ISSUE TITLE
Unable to install package home-connect-async==0.7.5

### ISSUE THREAD

**Issue by Mitch73-2** [ekutner/home-connect-hass#171]
I am running on raspberry pi4: 
Home Assistant 2023.3.0b0 
Supervisor 2023.01.1 
Operating System 9.5 
Frontend-versie: 20230222.0 - latest 

After updating to the latest version I get the following errors, before that everthing was working fine.

Home connect alt is not riunning anymore got these errors :
*Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 16:51:44 (2 occurrences)
Last logged: 16:51:53

Unable to install package home-connect-async==0.7.5: ERROR: Cannot install home-connect-async==0.7.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

*Logger: homeassistant.setup
Source: setup.py:205
First occurred: 16:51:53 (1 occurrences)
Last logged: 16:51:53

Setup failed for custom integration home_connect_alt: Requirements for home_connect_alt not found: ['home-connect-async==0.7.5'].

**Comment by alekslyse** [comment]
I can confirm this is on my first beta too, so seem to be a general issue

**Comment by tofrie** [comment]
Same here sine update to 2023.3 newest beta…

**Comment by victor-perez** [comment]
Same here, looks like 2023.3 release on first or March will break this integration.

**Comment by niklas389** [comment]
Yep, can confirm - happened to me with exactly the same error after the update.

**Comment by ekutner** [comment]
This is very annoying. They added a new library dependency to Home Assistant (pysiaalarm) which has a dependency on a very old version of a library that I am using. That has forced me to lower the version of the library that I'm using. It should work now but I'm not sure what might be the consequences and I don't have time to test it, so please let me know if you notice any new issues with the integration.
The fix is in beta 0.6.0-b5 so you'll have to enable beta versions in HACS to see it.

**Comment by Seafo** [comment]
Thank you for looking in to this!
Unfortunte the error persist also in beta5.
The difference is that it now says 0.7.6

Unable to install package home-connect-async==0.7.6: ERROR: Cannot install home-connect-async==0.7.6 because these package versions have conflicting dependencies

**Comment by Krocko** [comment]
@ekutner Is it because of the Python 3.11 support of Home Assistant?

**Comment by ekutner** [comment]
I didn't think so at first, but yes, it does seem related to 3.11 support. Please try version 0.6.0-b6 now. Let me know if you see issues with any special characters, like German umlauts.

**Comment by Mitch73-2** [comment]
The latest beta 0.6.0-b6 solved the problem for me. Great work.

**Comment by victor-perez** [comment]
I can also confirm that 0.6.0-b6 is working for me. Thanks for the quick fix

**Comment by ekutner** [comment]
Thank you for the updates.
