### ISSUE TITLE
after updating to 1.3.2 I dont receive events

### ISSUE THREAD

**Issue by rason92** [ekutner/home-connect-hass#524]
## Describe the bug
After updating to version 1.3.2, I am experiencing an issue with my dishwasher integration. Somehow, I now have the same device registered twice in Home Assistant. After the update, the entities reverted to the old dishwasher device, which I no longer use. 
As a result, some functionality no longer works, including receiving events from the device.  
I downgraded the integration back to version 1.3.1, after which everything worked normally again, including events. I deleted all the entities in the old dishwasher (vaatwasser oud). 
How can I solve this, so everything is working well in version 1.3.2?

## Version of the custom_component
1.3.2

## Configuration
I have not changed the default configuration for this device. the same device is added twice in home_connect_alt. I don't know why, maybe because i've changed soms entity-id's in the old device? Because of this, maybe the home_connect_alt intergration added a new device or something? 
<img width="1107" height="545" alt="Image" src="https://github.com/user-attachments/assets/d61a0bba-b77e-4947-a854-1f7ea1f53a6d" />

## Debug log
The error appears in the log as follows:

Logger: custom_components.home_connect_alt
Source: custom_components/home_connect_alt/__init__.py:395
Integration: Home Connect Alt (documentation, issues)
First occurred: 21:43:21 (2 occurrences)
Last logged: 21:43:21

No device found for appliance 011090388878000094, cannot publish event BSH.Common.Event.ProgramAborted = BSH.Common.EnumType.EventPresentState.Present
No device found for appliance 011090388878000094, cannot publish event Dishcare.Dishwasher.Event.SaltNearlyEmpty = BSH.Common.EnumType.EventPresentState.Present

**Comment by ekutner** [comment]
This should be fixed in 1.3.3-b1 but you may have to uninstall and re-install the integration

**Comment by Diegocampy** [comment]
Thanks @ekutner update and now all work fine

**Comment by ekutner** [comment]
That just shows the option exists in general. It is not likely that it just disappeared because the integration doesn't delete entities. Use the developer tools to look for the entity above

**Comment by cjborchert** [comment]
Here's the relevant part of the debug log before I removed and reinstalled the integration. In this log, I manually reloaded the integration at a moment when it had many of these disabled entitied (not remove/reinstall). After reloading those entities were still disabled.

[home-assistant_home_connect_alt_2025-11-16T07-35-05.453Z.log](https://github.com/user-attachments/files/23567252/home-assistant_home_connect_alt_2025-11-16T07-35-05.453Z.log)

It's all working now for me, but not sure exaclty what I did that corrected the issue. Perhaps this helps pinpoint something.

**Comment by czbird77** [comment]
I upgraded to 1.3.3-b1 but this still persisted. When I call the API directly, I get correct states, but Home Connect Alt says different. Since I have automations triggered by appliance-door state, this was no longer acceptable for me. Sorry, moved to Home Connect Local for now, I'll reconsider returning when the basics are working again.
